GO
SET IDENTITY_INSERT [dbo].[contract_numbering_formats] ON 

INSERT [dbo].[contract_numbering_formats] ([id], [name], [description], [pattern], [example], [prefix], [suffix], [fixed_code], [sequence_reset], [sequence_length], [is_active], [last_sequence], [last_reset_date], [created_at]) VALUES (1, N'Sheria360 Standard Format', N'Your current format with fixed prefix', N'PREFIXSEQ/MM/YYYY', N'S360/SCM/070/001/08/2023', N'CA/SCM/070/', NULL, NULL, N'never', 3, 1, 39, CAST(N'2026-01-16' AS Date), CAST(N'2026-01-15T00:57:35.7471719' AS DateTime2))
INSERT [dbo].[contract_numbering_formats] ([id], [name], [description], [pattern], [example], [prefix], [suffix], [fixed_code], [sequence_reset], [sequence_length], [is_active], [last_sequence], [last_reset_date], [created_at]) VALUES (2, N'Monthly Reset', N'Resets sequence each month', N'PREFIX/YYYY/MM/SEQ', N'CT/2023/08/001', N'CT', NULL, NULL, N'monthly', 3, 0, 0, NULL, CAST(N'2026-01-15T00:57:35.7481734' AS DateTime2))
INSERT [dbo].[contract_numbering_formats] ([id], [name], [description], [pattern], [example], [prefix], [suffix], [fixed_code], [sequence_reset], [sequence_length], [is_active], [last_sequence], [last_reset_date], [created_at]) VALUES (3, N'Department Monthly', N'Includes department code', N'PREFIX/DEPT/YYYY/MM/SEQ', N'CT/FIN/2023/08/001', N'CT', NULL, NULL, N'monthly', 3, 0, 0, NULL, CAST(N'2026-01-15T00:57:35.7481734' AS DateTime2))
INSERT [dbo].[contract_numbering_formats] ([id], [name], [description], [pattern], [example], [prefix], [suffix], [fixed_code], [sequence_reset], [sequence_length], [is_active], [last_sequence], [last_reset_date], [created_at]) VALUES (4, N'Yearly Reset', N'Resets sequence each year', N'PREFIX/YYYY/SEQ', N'CT/2023/001', N'CT', NULL, NULL, N'yearly', 4, 0, 0, NULL, CAST(N'2026-01-15T00:57:35.7481734' AS DateTime2))
INSERT [dbo].[contract_numbering_formats] ([id], [name], [description], [pattern], [example], [prefix], [suffix], [fixed_code], [sequence_reset], [sequence_length], [is_active], [last_sequence], [last_reset_date], [created_at]) VALUES (5, N'Continuous', N'Never resets sequence', N'PREFIX/SEQ', N'CT/0001', N'CT', NULL, NULL, N'never', 5, 0, 0, NULL, CAST(N'2026-01-15T00:57:35.7491740' AS DateTime2))
SET IDENTITY_INSERT [dbo].[contract_numbering_formats] OFF
GO
