<?php

echo "<div class=\"primary-style\">\r\n<div class=\"modal fade modal-container modal-resizable\">\r\n    <div class=\"modal-dialog modal-lg\">\r\n        <div class=\"modal-content\">\r\n            <div class=\"modal-header\">\r\n                <h4 class=\"modal-title\">";
echo $this->lang->line("add_matter_case");
echo "</h4>\r\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n            </div>\r\n            <div class=\"modal-body\" id=\"modal-body-add-case\">\r\n                <div id=\"legal-matter-add-form-container\" class=\"col-md-12 m-0 p-0 padding-10\">\r\n                    ";
echo form_open(current_url(), "class=\"form-horizontal\" novalidate id=\"legal-matter-add-form\"");
echo "                    ";
echo form_input(["id" => "action", "value" => "add_legal_matter", "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "send_notifications_email", "id" => "send_notifications_email", "value" => $hide_show_notification, "type" => "hidden"]);
echo "                    ";
echo form_input(["id" => "all-users-provider-group", "value" => $allUsersProviderGroupId, "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "externalizeLawyers", "id" => "externalizeLawyers", "value" => "no", "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "category", "id" => "category", "value" => $selected_values["category"], "type" => "hidden"]);
echo "                    ";
echo form_input(["id" => "arrival-date-hidden", "value" => $selected_values["today"], "type" => "hidden"]);
echo "                    ";
echo form_input(["id" => "filed-on-hidden", "value" => $selected_values["today"], "type" => "hidden"]);
echo "                    ";
echo form_input(["id" => "due-date-hidden", "value" => isset($selected_values["dueDate"]) ? $selected_values["dueDate"] : "", "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "assignment_id", "id" => "assignment-id", "value" => $assignments["id"], "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "assignment_relation", "id" => "assignment-relation", "value" => $assignments["assignment_relation"], "type" => "hidden"]);
echo "                    ";
echo form_input(["name" => "user_relation", "id" => "user-relation", "value" => $assignments["user_id"], "type" => "hidden"]);
echo "                    ";
echo form_input(["id" => "related-assigned-team", "value" => $assignments["assigned_team"], "type" => "hidden"]);
echo "                    <div class=\"col-md-12 p-0\" id=\"required-fields-matter-demo\">\r\n                        <div class=\"col-md-12 p-0 mb-10\">\r\n                            <div class=\"row m-0 form-group col-md-12 p-0 col-xs-12\">\r\n                                <label class=\"control-label col-md-3 pr-0 required col-xs-5\">";
echo $this->lang->line("subject_Case");
echo "</label>\r\n                                <div class=\"col-md-8 pr-0\">\r\n                                    ";
echo form_input(["dir" => "auto", "name" => "subject", "id" => "subject", "class" => "form-control", "autocomplete" => "stop", "value" => $selected_values["container_common_fields"]["containerSubject"] ?? ""]);
echo "                                    <div data-field=\"subject\" class=\"inline-error d-none\"></div>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"col-md-12 p-0 form-group row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 required col-xs-5\">";
echo $this->lang->line("case_type_case");
echo "</label>\r\n                            <div class=\"col-md-8 pr-0 col-xs-12 row no-margin\">\r\n                                <div class=\"col-md-11 p-0 margin-bottom-5 col-xs-10\">\r\n                                    <select name=\"case_type_id\"  id=\"case_type_id\" class=\"form-control select-picker\" data-live-search=\"true\" data-field=\"administration-case_types\" data-size=\"";
echo $this->session->userdata("max_drop_down_length");
echo "\">\r\n                                        <option value=\"\">";
echo $this->lang->line("none");
echo "</option>\r\n                                        ";
foreach ($legalCaseTypes as $key => $value) {
    $selected = "";
    $containtainerCaseType = $selected_values["container_common_fields"]["containerCaseType"]?? "";
    if ($systemPreferences["caseTypeProjectId"] == $value["id"] || $containtainerCaseType== $value["id"]) {
        $selected = " selected=\"selected\"";
    }
    echo "<option value=\"";
    echo $value["id"];
    echo "\" ";
    echo $selected;
    echo " legalMatterSLA='";
    echo $value["litigationSLA"];
    echo "' >";
    echo $value["name"];
    echo "</option>";
}
echo "                                        ?>\r\n                                    </select>\r\n                                </div>\r\n                                <div class=\"col-md-1 p-0 col-xs-2\">\r\n                                    <a href=\"javascript:;\" onclick=\"quickAdministrationDialog('case_types', jQuery('#legal-matter-dialog'), true, 'corporate');\" class=\"btn btn-link\"><i class=\"fa-solid fa-square-plus p-1 font-18\"> </i></a>\r\n                                </div>\r\n                                <div data-field=\"case_type_id\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\" id=\"arrival-date-container\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5 required\">";
echo $this->lang->line("arrival_date");
echo "</label>\r\n                            <div class=\"col-md-8 pr-0 col-xs-10 row no-margin\">\r\n                                <div class=\"input-group date p-0 date-picker\" id=\"arrival-date-add-new\">\r\n                                    ";
echo form_input(["name" => "caseArrivalDate", "id" => "arrival-date-input", "placeholder" => "YYYY-MM-DD", "class" => "form-control"], $selected_values["container_common_fields"]["arrival_date"] ?? $selected_values["today"]);
echo "                                    <span class=\"input-group-addon\"><i class=\"fa fa-calendar purple_color p-9 cursor-pointer-click\"></i></span>\r\n                                </div>\r\n                                ";
if ($systemPreferences["hijriCalendarConverter"]) {
    echo "                                    <div class=\"col-md-3 p-0 col-xs-2 visualize-hijri-date\"><a href=\"javascript:;\" id=\"date-conversion\" onclick=\"HijriConverter(jQuery('#arrival-date-add-new', '#legal-matter-dialog'));\" title=\"";
    echo $this->lang->line("hijri_date_converter");
    echo "\" class=\"btn btn-link\">";
    echo $this->lang->line("hijri");
    echo "</a></div>\r\n                                ";
}
echo "                                <div data-field=\"caseArrivalDate\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"col-md-12 p-0 mb-10\" id=\"optional-fields-matter-demo\">\r\n                        <div class=\"form-group d-flex p-0 m-0 col-xs-12\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("description_Case");
echo "&nbsp; <span role=\"button\" class=\"tooltip-title\" title=\"";
echo $this->lang->line("matter_description_help");
echo "\" ><i class=\"fa-solid fa-circle-question purple_color\"></i></span></label>\r\n                            <div class=\"col-md-8 pr-0\">\r\n                                ";
echo form_textarea(["name" => "description", "id" => "description", "class" => "form-control", "rows" => "5", "cols" => "0", "value" => $selected_values["container_common_fields"]["containerDescription"] ?? ""]);
echo "                                <div data-field=\"description\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 pr-0 row m-0 mb-10\">\r\n                        <label class=\"control-label col-md-3 col-xs-5\">";
echo $this->lang->line("client_name");
echo "</label>\r\n                        <select name=\"clientType\" id=\"client-type\" class=\"form-control col-md-8 select-picker\" tabindex=\"-1\">\r\n                            <option value=\"company\" ";
echo isset($selected_values["container_common_fields"]["client_data"]["type"]) ? $selected_values["container_common_fields"]["client_data"]["type"] == "Company" ? "selected=\"selected\"" : "" : "";
echo ">";
echo $this->lang->line("company_or_group");
echo "</option>\r\n                            <option value=\"contact\" ";
echo isset($selected_values["container_common_fields"]["client_data"]["type"]) ? $selected_values["container_common_fields"]["client_data"]["type"] == "Person" ? "selected=\"selected\"" : "" : "";
echo ">";
echo $this->lang->line("contact");
echo "</option>\r\n                        </select>\r\n                    </div>\r\n                    <div class=\"col-md-12 form-group pr-0 mb-10 row no-margin\">\r\n                        <label class=\"control-label col-md-3 col-xs-12\">&nbsp;</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10 p-0\">\r\n                            ";
echo form_input(["name" => "contact_company_id", "id" => "contact-company-id", "value" => $selected_values["container_common_fields"]["client_data"]["member_id"] ?? "", "type" => "hidden"]);
echo "                            ";
echo form_input(["name" => "clientLookup", "id" => "client-lookup", "value" => $selected_values["container_common_fields"]["client_data"]["name"] ?? "", "class" => "form-control lookup", "title" => $this->lang->line("start_typing")]);
echo "                            <div data-field=\"contact_company_id\" class=\"inline-error d-none\"></div>\r\n                        </div>\r\n                        <div class=\"col-md-12 p-0 row m-0 autocomplete-helper\">\r\n                            <div class=\"col-md-3\">\r\n                            </div>\r\n                            <div class=\"col-md-8\">\r\n                                <div class=\"inline-text\">";
echo $this->lang->line("helper_autocomplete");
echo "</div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 ";
echo $assignments["visible_assigned_team"] ? "" : "d-none";
echo " row m-0 mb-10\" id=\"assigned-team-container\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("provider_group");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            <div class=\"col-md-12 p-0\">\r\n                                ";
echo form_dropdown("provider_group_id", $Provider_Groups, $selected_values["container_common_fields"]["assigned_team"] ?? $assignments["assigned_team"], "id=\"provider-group-id\" data-live-search=\"true\" class=\"form-control select-picker\" data-size=\"" . $this->session->userdata("max_drop_down_length") . "\"");
echo "                                <div data-field=\"provider_group_id\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 ";
echo $assignments["visible_assignee"] ? "" : "d-none";
echo " row m-0 mb-10\" id=\"assignee-container\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("assignee");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            <div class=\"col-md-12 p-0\">\r\n                                ";
echo form_dropdown("user_id", $usersProviderGroup, $selected_values["container_common_fields"]["containerAssignee"] ?? (isset($assignments["user_id"]) ? $assignments["user_id"] : ""), "id=\"user-id\" data-live-search=\"true\" class=\"form-control select-picker\" data-size=\"" . $this->session->userdata("max_drop_down_length") . "\"");
echo "                                <div data-field=\"user_id\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"col-md-12 form-group p-0 case-privacy-container row m-0 mb-10\" id=\"case-privacy-container\">\r\n                        <label class=\"control-label col-md-3 col-xs-12 pr-0\">";
echo $this->lang->line("shared_with");
echo "</label>\r\n                        <div class=\"col-md-6 col-xs-8\">\r\n                            <label class=\"shared-with-label\">";
echo $this->lang->line("everyone");
echo "</label>\r\n                            <div class=\"lookup-box-container margin-bottom input-group col-md-12 p-0 d-none users-lookup-container\">\r\n                                ";
echo form_input(["id" => "lookup-case-users", "name" => "lookupCaseUsers", "class" => "form-control users-lookup", "title" => $this->lang->line("start_typing")]);
echo "                                <span class=\"input-group-addon bs-caret users-lookup-icon\" id=\"shared-with-users\" onclick=\"jQuery('#lookup-case-users', '#legal-matter-dialog').focus();\"><span class=\"caret\"></span></span>\r\n                            </div>\r\n                            <div id=\"selected-watchers\" class=\"height-auto m-0 d-none\">\r\n                                <div class=\"flex-item-box row multi-option-selected-items no-margin w-100 height-30px\">\r\n                                    <span>";
echo $this->lang->line("case_creator");
echo "</span>\r\n                                </div>\r\n                                <div class=\"flex-item-box row multi-option-selected-items no-margin w-100 height-30px\">\r\n                                    <span>";
echo $this->lang->line("assignee");
echo "</span>\r\n                                </div>\r\n                            </div>\r\n                            <div data-field=\"case_watchers\" class=\"inline-error d-none padding-5\"></div>\r\n                        </div>\r\n                        <div class=\"col-md-2 p-0 col-xs-4\">\r\n                            <a class=\"btn btn-default btn-link float-right p-0\" id=\"privateLink\" href=\"javascript:;\" onClick=\"setAsPrivate(jQuery('#case-privacy-container', '#legal-matter-dialog'), 'cases', '', '', '', true);\">";
echo $this->lang->line("set_as_private");
echo "</a>\r\n                            <a class=\"d-none btn btn-default btn-link float-right p-0\" id=\"publicLink\" href=\"javascript:;\" onClick=\"setAsPublic(jQuery('#case-privacy-container', '#legal-matter-dialog'), 'cases', true);\">";
echo $this->lang->line("set_as_public");
echo "</a>\r\n                            ";
echo form_input(["id" => "private", "name" => "private", "value" => "no", "type" => "hidden"]);
echo "                        </div>\r\n                        <div class=\"col-md-12 d-flex p-0 autocomplete-helper d-none\">\r\n                            <div class=\"col-md-3\"></div>\r\n                            <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                                <div class=\"inline-text\">";
echo $this->lang->line("helper_autocomplete");
echo "</div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 row m-0 mb-10\" id=\"filed-on-date-container\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">\r\n                            ";
echo $this->lang->line("filed_on");
echo "                            &nbsp; <span class=\"tooltip-title\" title=\"";
echo $this->lang->line("matter_filed_on_helper");
echo "\"><i class=\"fa-solid fa-circle-question purple_color\"></i></span>\r\n                        </label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            <div class=\"input-group date col-md-12 p-0 date-picker\" id=\"filed-on\">\r\n                                ";
echo form_input(["name" => "arrivalDate", "id" => "filed-on-input", "placeholder" => "YYYY-MM-DD", "value" => $selected_values["today"], "class" => "form-control"]);
echo "                                <span class=\"input-group-addon\"><i class=\"fa fa-calendar purple_color p-9 cursor-pointer-click\"></i></span>\r\n                            </div>\r\n                            ";
if ($systemPreferences["hijriCalendarConverter"]) {
    echo "                                <div class=\"col-md-3 p-0 col-xs-2 visualize-hijri-date\"><a href=\"javascript:;\" id=\"date-conversion\" onclick=\"HijriConverter(jQuery('#filed-on', '#legal-matter-dialog'));\" title=\"";
    echo $this->lang->line("hijri_date_converter");
    echo "\" class=\"btn btn-link\">";
    echo $this->lang->line("hijri");
    echo "</a></div>\r\n                            ";
}
echo "                            <div data-field=\"arrivalDate\" class=\"inline-error d-none\"></div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 row m-0 mb-10\" id=\"due-date-container\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("due_date");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            <div class=\"input-group date col-md-12 p-0 date-picker\" id=\"due-date-add-new\">\r\n                                ";
echo form_input(["name" => "dueDate", "id" => "due-date-input", "placeholder" => "YYYY-MM-DD", "class" => "form-control", "value" => isset($selected_values["dueDate"]) ? $selected_values["dueDate"] : ""]);
echo "                                <span class=\"input-group-addon\"><i class=\"fa fa-calendar purple_color p-9 cursor-pointer-click\"></i></span>\r\n                            </div>\r\n                            ";
if ($systemPreferences["hijriCalendarConverter"]) {
    echo "    \r\n                                <div class=\"col-md-3 p-0 col-xs-2 visualize-hijri-date\"><a href=\"javascript:;\" id=\"date-conversion\" onclick=\"HijriConverter(jQuery('#due-date-add-new', '#legal-matter-dialog'));\" title=\"";
    echo $this->lang->line("hijri_date_converter");
    echo "\" class=\"btn btn-link\">";
    echo $this->lang->line("hijri");
    echo "</a></div>\r\n                            ";
}
echo "                            <div class=\"col-md-10 p-0 ";
echo isset($selected_values["dueDate"]) ? "" : "d-none";
echo "\" id=\"notify-me-before-link\">\r\n                                <a href=\"javascript:;\" onclick=\"notifyMeBefore(jQuery('#legal-matter-dialog'));\">";
echo $this->lang->line("notify_me_before");
echo "</a>\r\n                            </div>\r\n                            <div data-field=\"dueDate\" class=\"inline-error d-none\"></div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"col-md-12 p-0 form-inline form-group d-none\" id=\"notify-me-before-container\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("notify_me_before");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\" id=\"notify-me-before\">\r\n                            <div class=\"d-flex mb-10\">\r\n                                ";
echo form_input(["name" => "notify_me_before[time]", "class" => "form-control", "value" => $systemPreferences["reminderIntervalDate"], "id" => "notify-me-before-time", "disabled" => true]);
echo "                                ";
echo form_dropdown("notify_me_before[time_type]", $notify_me_before_time_types, "", "class=\"form-control select-picker mx-2\" id=\"notify-me-before-time-type\" disabled");
echo "                                <label class=\"control-label\">";
echo $this->lang->line("reminder_by");
echo "</label>\r\n                            </div>\r\n                            ";
echo form_dropdown("notify_me_before[type]", $notify_me_before_types, "", "class=\"form-control select-picker\" id=\"notify-me-before-type\" disabled");
echo "                            <a href=\"javascript:;\" onclick=\"hideRemindMeBefore(jQuery('#legal-matter-dialog'));\" class=\"btn btn-link p-0\">\r\n                                <i class=\"icon fa-solid fa-xmark\"></i>\r\n                            </a>\r\n                            <div data-field=\"notify_before\" class=\"inline-error d-none\"></div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("reference_case");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            ";
echo form_input(["dir" => "auto", "name" => "internalReference", "class" => "form-control", "value" => $selected_values["container_common_fields"]["internal_reference"] ?? ""]);
echo "                            <div data-field=\"internalReference\" class=\"inline-error d-none\"></div>\r\n                        </div>\r\n                        <div class=\"col-md-12 autocomplete-helper row no-margin\">\r\n                            <div class=\"col-md-3 pr-0\">\r\n                            </div>\r\n                            <div class=\"col-md-8 col-xs-10\">\r\n                                <div class=\"inline-text\">";
echo $this->lang->line("helper_reference");
echo "</div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                        <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("case_priority");
echo "</label>\r\n                        <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                            <select name=\"priority\" class=\"form-control select-picker\"  id=\"priority\" data-live-search=\"true\">\r\n                                ";
$selected = "";
foreach ($priorities as $key => $value) {
    if ($key == $selected_values["priority"]) {
        $selected = "selected";
    } else {
        $selected = "";
    }
    echo "                                    <option data-icon=\"priority-";
    echo $key;
    echo "\" ";
    echo $selected;
    echo " value=\"";
    echo $key;
    echo "\">";
    echo $value;
    echo "</option>\r\n                                    ";
}
echo "                            </select>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"col-md-12 p-0 show-rest-fields\">\r\n                        <div class=\"form-group col-md-12 d-flex p-0\">\r\n                            <div class=\"col-md-3\"></div>\r\n                            <div class=\"col-md-8 pr-0\">\r\n                                <a href=\"javascript:;\" onclick=\"showMoreFields(jQuery('#legal-matter-dialog'), jQuery('#lookup-requested-by', '#legal-matter-dialog'));\">";
echo $this->lang->line("more_fields");
echo "</a>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"d-none container-hidden-fields\">\r\n                        <div class=\"col-md-12 less-field-divider\">\r\n                            <hr>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("matter_container");
echo "</label>\r\n                            <div class=\"col-md-8 d-flex pr-0 col-xs-10\">\r\n                                <div class=\"col-md-10 p-0\">\r\n                                    ";
echo form_input(["name" => "legalCaseRelatedContainerId", "id" => "legal-case-related-container-id", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "legalCaseRelatedSubject", "id" => "legal-case-related-container-lookup", "value" => $selected_values["container_common_fields"]["containerSubject"] ?? "", "class" => "lookup form-control", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing"), "onblur" => "checkLookupValidity(jQuery(this), jQuery('#legalCaseRelatedContainerId')); if (this.value === '') { jQuery('#legal-case-related-container-link').addClass('d-none'); }"]);
echo "                                </div>\r\n                                <div class=\"col-md-2 p-0 col-xs-2 text-center\">\r\n                                    <a href=\"javascript:;\" id=\"legal-case-related-container-link\" target=\"_blank\" class=\"btn btn-link d-none\"></a>\r\n                                </div>\r\n                                <div data-field=\"legal-case-related-container-id\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                            <div class=\"col-md-12 p-0 d-flex autocomplete-helper\">\r\n                                <div class=\"col-md-3 pr-0 col-xs-1\" >&nbsp;</div>\r\n                                <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                                    <div class=\"inline-text\">";
echo $this->lang->line("helper_autocomplete");
echo "</div>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("matter_case_stage");
echo "</label>\r\n                            <div class=\"col-md-8 d-flex pr-0 col-xs-12\">\r\n                                <div class=\"col-md-10 p-0 col-xs-10\">\r\n                                    ";
echo form_dropdown("legal_case_stage_id", $corporateCaseStages, "", "class=\"form-control select-picker\" id=\"legal_case_stage_id\" data-live-search=\"true\" data-field=\"administration-case_stages\" data-size=\"" . $this->session->userdata("max_drop_down_length") . "\"");
echo "                                    <div data-field=\"legal_case_stage_id\" class=\"inline-error d-none\"></div>\r\n                                </div>\r\n                                <div class=\"col-md-2 p-0 col-xs-2\">\r\n                                    <a href=\"javascript:;\" onclick=\"quickAdministrationDialog('case_stages', jQuery('#legal-matter-dialog'), true, 'corporate')\" class=\"btn btn-link\"><i class=\"fa-solid fa-square-plus p-1 font-18\"> </i></a>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("requested_by");
echo "</label>\r\n                            <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                                <div class=\"col-md-12 p-0\">\r\n                                    ";
echo form_input(["name" => "requestedBy", "id" => "requested-by", "value" => "", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "requestedByName", "id" => "lookup-requested-by", "value" => "", "class" => "form-control lookup", "title" => $this->lang->line("start_typing")]);
echo "                                </div>\r\n                                <div data-field=\"requestedBy\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                            <div class=\"col-md-12 p-0 d-flex autocomplete-helper\">\r\n                                <div class=\"col-md-3 pr-0 col-xs-1\" >&nbsp;</div>\r\n                                <div class=\"col-md-8 pr-0 col-xs-10\">\r\n                                    <div class=\"inline-text\">";
echo $this->lang->line("helper_autocomplete");
echo "</div>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("caseValue");
echo " <div class=\"help-block smaller_font\">";
echo isset($systemPreferences["caseValueCurrency"]) && $systemPreferences["caseValueCurrency"] != "" ? "(" . $systemPreferences["caseValueCurrency"] . ")" : "";
echo "</div></label>\r\n                            <div class=\"col-md-8 pr-0 col-xs-12\">\r\n                                <div class=\"col-md-5 p-0 col-xs-10\">\r\n                                    ";
echo form_input(["value" => "", "id" => "caseValue", "class" => "form-control", "name" => "caseValue"]);
echo "                                </div>\r\n\r\n                                <div data-field=\"caseValue\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"form-group col-md-12 p-0 row m-0 mb-10\">\r\n                            <label class=\"control-label col-md-3 pr-0 col-xs-5\">";
echo $this->lang->line("estimated_effort");
echo "</label>\r\n                            <div class=\"col-md-8 pr-0 col-xs-12\">\r\n                                <div class=\"col-md-5 col-sm-7 col-xs-12 p-0\">\r\n                                    ";
echo form_input(["name" => "estimatedEffort", "class" => "form-control", "onblur" => "convertMinsToHrsMins(jQuery(this));"]);
echo "                                </div>\r\n                                <div class=\"col-md-7 col-sm-5 col-xs-12 estimated-effort-hour vertical-aligned-tooltip-icon-container\">\r\n                                    <span>(e.g. 1h 20m)</span>\r\n                                    <span class=\"tooltip-title\" title=\"";
echo $this->lang->line("supported_time_units");
echo "\"><i class=\"fa-solid fa-circle-question purple_color\"></i></span>\r\n                                </div>\r\n                                <div data-field=\"estimatedEffort\" class=\"inline-error d-none\"></div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"col-md-12 p-0 hide-rest-fields d-none\">\r\n                            <div class=\"form-group col-md-12 p-0 d-flex row m-0 mb-10\">\r\n                                <div class=\"col-md-3\"></div>\r\n                                <div class=\"col-md-8 pr-0\">\r\n                                    <a href=\"javascript:;\" onclick=\"showLessFields(jQuery('#legal-matter-dialog'));\"><i class=\"fa fa-angle-double-up\"></i>&nbsp;";
echo $this->lang->line("less_fields");
echo "</a>\r\n                                </div>\r\n                            </div>\r\n\r\n                        </div>\r\n                        ";
form_close();
echo "                    </div>\r\n                </div>\r\n            </div><!-- /.modal-body -->\r\n            <div class=\"modal-footer justify-content-between\">\r\n                ";
$this->load->view("templates/send_email_option_template", ["type" => "add_matter_case", "container" => "#legal-matter-dialog"]);
echo "                <div>\r\n                <span class=\"loader-submit\"></span>\r\n                <button type=\"button\" class=\"btn save-button modal-save-btn btn-info\" id=\"case-submit\">";
echo $this->lang->line("save");
echo "</button>\r\n                <button type=\"button\" class=\"close_model no_bg_button\" data-dismiss=\"modal\">";
echo $this->lang->line("cancel");
echo "</button>\r\n                </div>\r\n            </div>\r\n        </div><!-- /.modal-content -->\r\n    </div><!-- /.modal-dialog -->\r\n</div><!-- /.modal -->\r\n</div>\r\n<script>\r\n\r\n    jQuery(document).ready(function(){\r\n\r\n        jQuery('.tooltip-title').tooltipster({\r\n            contentAsHTML: true,\r\n            timer: 22800,\r\n            animation: 'grow',\r\n            delay: 200,\r\n            theme: 'tooltipster-default',\r\n            touchDevices: false,\r\n            trigger: 'hover',\r\n            maxWidth: 350,\r\n            interactive: true\r\n        });\r\n\r\n\r\n        let case_types_due_conditions = ";
echo $case_type_due_conditions;
echo ";\r\n        jQuery('#case_type_id').on('change', function() {\r\n            let dueIn =   setDueDateWithConditions(case_types_due_conditions,jQuery('#case_type_id').find(\":selected\").val(),\r\n        jQuery('#contact-company-id').val(),jQuery('#client-type').find(\":selected\").val(),jQuery('#priority').find(\":selected\").val());\r\n        setDueDate( dueIn  , '#legal-matter-dialog')\r\n});\r\njQuery('#contact-company-id').on('change', function() {\r\n    let dueIn = setDueDateWithConditions(case_types_due_conditions,jQuery('#case_type_id').find(\":selected\").val(),\r\n        jQuery('#contact-company-id').val(),jQuery('#client-type').find(\":selected\").val(),jQuery('#priority').find(\":selected\").val());\r\n        setDueDate( dueIn  , '#legal-matter-dialog')\r\n});\r\njQuery('#client-type').on('change', function() {\r\n    let dueIn = setDueDateWithConditions(case_types_due_conditions,jQuery('#case_type_id').find(\":selected\").val(),\r\n        jQuery('#contact-company-id').val(),jQuery('#client-type').find(\":selected\").val(),jQuery('#priority').find(\":selected\").val());\r\n\r\n        setDueDate( dueIn  , '#legal-matter-dialog')\r\n});\r\n        jQuery('#priority').on('change', function() {//set on change of each one to call due date on change of any of these 3\r\n        let dueIn = setDueDateWithConditions(case_types_due_conditions,jQuery('#case_type_id').find(\":selected\").val(),\r\n        jQuery('#contact-company-id').val(),jQuery('#client-type').find(\":selected\").val(),jQuery('#priority').find(\":selected\").val());\r\n\r\n        setDueDate( dueIn  , '#legal-matter-dialog')\r\n});\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    });\r\n   function setDueDateWithConditions(case_types_due_conditions,caseTypeId,clientId,clientTypeId,priority){\r\n     let returned_due_in = -1;\r\n     let isDueInSet = false ;\r\n     for (let i = 0; i < case_types_due_conditions.length; i++) {\r\n\r\n         if(case_types_due_conditions[i].id == caseTypeId){\r\n          if(case_types_due_conditions[i].due_conditions != null && case_types_due_conditions[i].due_conditions.length > 0){\r\n            for (let j = 0; j < case_types_due_conditions[i].due_conditions.length; j++) {\r\n                let due_condition = case_types_due_conditions[i].due_conditions[j];\r\n              if(\r\n                  (\r\n                  (parseInt(due_condition.company_id) == parseInt(clientId) && clientTypeId == 'company')\r\n              ||(parseInt(due_condition.contact_id) == parseInt(clientId) && clientTypeId == 'contact')\r\n               || (due_condition.client_id == null && clientId == ''))\r\n              && (due_condition.priority == priority || due_condition.priority == 'all')){\r\n                  returned_due_in =  due_condition.due_in;\r\n                  return returned_due_in;\r\n                  isDueInSet = true;\r\n                  return ;\r\n              }\r\n            }\r\n          }else if(isDueInSet == false){\r\n            returned_due_in =  case_types_due_conditions[i].litigationSLA;\r\n\r\n          }\r\n          returned_due_in =  case_types_due_conditions[i].litigationSLA ;\r\n         }\r\n\r\n       }\r\n       if(returned_due_in == null || returned_due_in == -1){\r\n             returned_due_in =0;\r\n         }\r\n         return returned_due_in;\r\n       setDueDate( returned_due_in  , '#legal-matter-dialog')\r\n\r\n    }\r\n\r\n    addMatterDemo();\r\n</script>";

?>