<?php

echo "<div id=\"grid-scrollable\" class=\"row no-margin\">\r\n    <div class=\"col-md-12 k-padding no-padding\">\r\n        ";
echo form_open("", "name=\"expenseSearchFilters\" id=\"expenseSearchFilters\" method=\"post\" class=\"form-horizontal\" role=\"form\"");
echo "        <div id=\"filtersFormWrapper\" class=\"card card-default\" style=\"display: none;\">\r\n            <div class=\"card-header\">\r\n                <h4>";
echo $this->lang->line("search_expenses_filters");
echo "</h4>\r\n            </div>         \r\n            <div class=\"card-body\">\r\n                ";
echo form_input(["name" => "take", "value" => "20", "type" => "hidden"]);
echo "                ";
echo form_input(["name" => "skip", "value" => "0", "type" => "hidden"]);
echo "                ";
echo form_input(["name" => "page", "value" => "1", "type" => "hidden"]);
echo "                ";
echo form_input(["name" => "pageSize", "value" => "20", "type" => "hidden"]);
echo "                ";
echo form_input(["name" => "filter.logic", "id" => "defaultFilterLogic", "value" => "and", "type" => "hidden"]);
echo "                ";
echo form_input(["name" => "quickSearch.logic", "id" => "", "value" => "and", "type" => "hidden"]);
echo "                ";
echo form_input(["id" => "display-columns", "value" => implode(",", $selected_columns), "type" => "hidden"]);
echo "                ";
echo form_input(["id" => "model", "value" => $model, "type" => "hidden"]);
echo "\r\n                <div class=\"col-md-12 no-margin\">\r\n                    <div class=\"form-group d-none\">\r\n                        <div class=\"col-md-4\">\r\n                            ";
echo form_input(["name" => "quickSearch.filters[0].filters[0].field", "id" => "quickSearchFilterExpenseField", "value" => "description", "type" => "hidden"]);
echo "                            ";
echo form_input(["name" => "quickSearch.filters[0].filters[0].operator", "id" => "quickSearchFilterExpenseOperator", "value" => "contains", "type" => "hidden"]);
echo "                            ";
echo form_input(["name" => "quickSearch.filters[0].filters[0].value", "id" => "quickSearchFilterExpenseValue", "class" => "form-control", "value" => "", "type" => "hidden"]);
echo "\r\n                            ";
if (isset($my_expenses) && $my_expenses) {
    echo "                                ";
    echo form_input(["name" => "quickSearch.filters[1].filters[0].field", "id" => "quickSearchFilterExpensePaidThroghField", "value" => "paidThroughID", "type" => "hidden"]);
    echo "                                ";
    echo form_input(["name" => "quickSearch.filters[1].filters[0].operator", "id" => "quickSearchFilterExpensePaidThroghOperator", "value" => "in", "type" => "hidden"]);
    echo "                                ";
    foreach ($user_paid_through_Accounts as $key => $value) {
        echo "                                    ";
        echo form_input(["name" => "quickSearch.filters[1].filters[0].value[]", "class" => "form-control", "value" => $value, "id" => "quickSearchFilterExpensePaidThroghValue", "type" => "hidden"]);
        echo "                                    ";
    }
}
echo "                        </div>\r\n                    </div>\r\n                    <div class=\"\">\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"expenseID\">\r\n                                <label class=\"control-label col-md-3\">";
echo $this->lang->line("expense_id");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[0].filters[0].field", "value" => "expenseID", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[0].filters[0].operator", $operatorsNumbers, "", "id=\"numberOpertator\" class=\"sf-operator form-control grid-filters-opertator\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "numberValue", "name" => "filter.filters[0].filters[0].value", "value" => "", "class" => "sf-value form-control grid-filters-input", "data-validation-engine" => "validate[funcCall[validateIntegers]]"]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" id=\"paidOnContainer\" sf-field=\"dated\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("paid_on");
echo "</label>\r\n                                <div class=\"col-md-3 \">\r\n                                    ";
echo form_input(["name" => "filter.filters[1].filters[0].field", "value" => "dated", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[1].filters[0].operator", "value" => "cast_eq", "class" => "sf-operator start-date-operator", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("dateOperator1", $operatorsDate, "", "id=\"paidOnOpertator\" class=\"sf-operator-list form-control\" onchange=\"onchangeOperatorsFiltersDate(this, 'paidOnContainer');\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "paidOnValue", "name" => "filter.filters[1].filters[0].value", "value" => "", "autocomplete" => "off", "class" => "sf-value form-control", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                                <div class=\" col-md-5 offset-md-6 margin-top\">\r\n                                    ";
echo form_input(["name" => "filter.filters[1].logic", "value" => "and", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[1].filters[1].field", "value" => "dated", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[1].filters[1].operator", "value" => "cast_lte", "class" => "sf-operator2", "type" => "hidden"]);
echo "                                    ";
echo form_input(["id" => "paidOnEndValue", "name" => "filter.filters[1].filters[1].value", "value" => "", "autocomplete" => "off", "class" => "sf-value2 form-control d-none end-date-filter", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"expenseCategoryId\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("expense_category");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[2].filters[0].field", "value" => "expenseCategoryId", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[2].filters[0].operator", $operatorsGroupList, "", "id=\"expenseCategoryOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    <select id=\"expenseCategoryValue\" name=\"filter.filters[2].filters[0].value\" multiple=\"multiple\" class=\"sf-value multi-select form-control\">";
foreach ($expense_categories as $expenses_category) {
    echo "<option value=\"";
    echo $expenses_category["id"];
    echo "\">";
    echo $expenses_category["name"];
    echo "</option>";
}
unset($expense_categories);
echo "</select>  \r\n                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"amount\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("amount");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[3].filters[0].field", "value" => "amount", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[3].filters[0].operator", $operatorsNumbers, "", "id=\"amountOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "amountValue", "name" => "filter.filters[3].filters[0].value", "value" => "", "class" => "sf-value form-control", "data-validation-engine" => "validate[funcCall[validateDecimals]]", "onkeydown" => "RemoveFormatMoney(this);", "onpaste" => "RemoveFormatMoney(this);"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\" sf-field=\"paidThroughID\">\r\n                            <div class=\"form-group row col-md-6\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("paid_through");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[5].filters[0].field", "value" => "paidThroughID", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[5].filters[0].operator", $operatorsGroupList, "", "id=\"paidThroughOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    <select  id=\"paidThroughValue\" name=\"filter.filters[5].filters[0].value\" multiple=\"multiple\" class=\"sf-value multi-select form-control\">";
foreach ($paid_through as $key => $record) {
    $selected = "";
    $disabled = "";
    if (isset($my_expenses) && $my_expenses) {
        if (in_array($key, $user_paid_through_Accounts)) {
            $selected = "selected = \"selected\"";
        }
        $disabled = "disabled = \"disabled\" ";
    }
    echo "<option " . $disabled . " " . $selected . " value=\"";
    echo $key;
    echo "\">";
    echo $record;
    echo "</option>";
}
unset($record);
echo "</select>                            \r\n                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"paymentMethod\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("payment_method");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[18].filters[0].field", "value" => "paymentMethod", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[18].filters[0].operator", $operatorsGroupList, "", "id=\"paymentMethodOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_dropdown("filter.filters[18].filters[0].value", $paymentMethod, "", "id=\"paymentMethodValue\" multiple=\"multiple\" class=\"sf-value multi-select form-control\"");
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"paid_through_account_number\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo sprintf($this->lang->line("account_type_account_number"), $this->lang->line("paid_through"));
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[4].filters[0].field", "value" => "paid_through_account_number", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[4].filters[0].operator", $operatorsText, "", "id=\"paid_through_account_numberOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "paid_through_account_numberValue", "name" => "filter.filters[4].filters[0].value", "value" => "", "class" => "sf-value form-control"]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"clientName\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("client_name_money");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[8].filters[0].field", "value" => "clientName", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[8].filters[0].operator", $operatorsList, "", "id=\"clientOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "clientValue", "name" => "filter.filters[8].filters[0].value", "value" => $clientNameFilter, "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing")]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"billingStatus\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("billing_status");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[7].filters[0].field", "value" => "billingStatus", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[7].filters[0].operator", $operatorsGroupList, "", "id=\"billingStatusOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_dropdown("filter.filters[7].filters[0].value", $billingStatuses, "", "id=\"billingStatusValue\" multiple=\"multiple\" class=\"sf-value multi-select form-control\"");
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"referenceNum\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("reference_number");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[17].filters[0].field", "value" => "referenceNum", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[17].filters[0].operator", $operatorsList, "", "id=\"referenceNumOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "referenceNum", "name" => "filter.filters[17].filters[0].value", "value" => "", "class" => "sf-value form-control"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"status\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("status");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[19].filters[0].field", "value" => "status", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[19].filters[0].operator", $operatorsGroupList, "", "id=\"statusOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_dropdown("filter.filters[19].filters[0].value", $statuses, "", "id=\"statusValue\" multiple=\"multiple\" class=\"sf-value multi-select form-control\"");
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"tax_number\">\r\n                                <label class=\"control-label col-md-3\">\r\n                                    ";
echo $this->lang->line("tax_number");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_hidden("filter.filters[20].filters[0].field", "tax_number");
echo "                                    ";
echo form_dropdown("filter.filters[20].filters[0].operator", $operatorsText, "", "id=\"TaxNumberOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input("filter.filters[20].filters[0].value", "", "id=\"TaxNumberValue\" class=\"sf-value form-control\"");
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"totalTax\">\r\n                                <label class=\"control-label col-md-3\">\r\n                                    ";
echo $this->lang->line("total_tax");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_hidden("filter.filters[21].filters[0].field", "totalTax");
echo "                                    ";
echo form_dropdown("filter.filters[21].filters[0].operator", $operatorsNumbers, "", "id=\"TotalTaxOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input("filter.filters[21].filters[0].value", "", "id=\"TotalTaxValue\" class=\"sf-value form-control\" onkeydown=\"RemoveFormatMoney(this);\" onpaste=\"RemoveFormatMoney(this);\" ");
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"subTotal\">\r\n                                <label class=\"control-label col-md-3\">\r\n                                    ";
echo $this->lang->line("sub_total");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_hidden("filter.filters[22].filters[0].field", "subTotal");
echo "                                    ";
echo form_dropdown("filter.filters[22].filters[0].operator", $operatorsNumbers, "", "id=\"SubTotalOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input("filter.filters[22].filters[0].value", "", "id=\"SubTotalValue\" class=\"sf-value form-control\" onkeydown=\"RemoveFormatMoney(this);\" onpaste=\"RemoveFormatMoney(this);\" ");
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\t\t\t\t\r\n                    <div class=\"row\">\r\n                        <div class=\"col-md-6 no-padding-right\">\r\n                            <h4>\r\n                                ";
echo $this->lang->line("more_filters_criteria");
echo "                                <label class=\"control-label\">\r\n                                    <a onclick=\"collapse('toggleDetails', 'advancedSearchFields', true);\r\n                                            fixFooterPosition();\" id=\"toggleDetails\" title=\"";
echo $this->lang->line("show_details");
echo "\" ><i class=\"dottedIcon\"></i></a>\r\n                                </label>\r\n                            </h4>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"d-none\" id=\"advancedSearchFields\">\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"supplier\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("vendor");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[6].filters[0].field", "value" => "supplier", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[6].filters[0].operator", $operatorsList, "", "id=\"vendorOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "vendorValue", "name" => "filter.filters[6].filters[0].value", "value" => $supplierNameFilter, "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing")]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"clientAccountID\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("client_account");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[9].filters[0].field", "value" => "clientAccountID", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[9].filters[0].operator", $operatorsList, "", "id=\"accountNameOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "accountNameValue", "value" => isset($client_account) && !empty($client_account) ? $client_account : "", "class" => "form-control lookup", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing"), "onblur" => "if (jQuery(this).val() === '') { jQuery('#clientAccountID').val(''); }"]);
echo "                                    ";
echo form_input(["id" => "clientAccountID", "name" => "filter.filters[9].filters[0].value", "value" => "", "class" => "sf-value form-control", "data-field" => "hidden-lookup-input", "type" => "hidden"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\t\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"client_account_number\">\r\n                                <label  class=\"control-label col-md-3\">";
echo sprintf($this->lang->line("account_type_account_number"), $this->lang->line("client_money"));
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[11].filters[0].field", "value" => "client_account_number", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[11].filters[0].operator", $operatorsText, "", "id=\"client_account_numberOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "client_account_numberValue", "name" => "filter.filters[11].filters[0].value", "value" => "", "class" => "sf-value form-control"]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"case_id\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("case");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[10].filters[0].field", "value" => "case_id", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[10].filters[0].operator", $operatorsList, "", "id=\"caseOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "caseValue", "name" => "filter.filters[10].filters[0].value", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("client_or_matter_placeholder"), "title" => $this->lang->line("client_or_matter_placeholder")]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\t\r\n\r\n\r\n\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"task_id\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("task");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[16].filters[0].field", "value" => "task_id", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[16].filters[0].operator", $operatorsList, "", "id=\"task_idOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "task_idValue", "name" => "filter.filters[16].filters[0].value", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("task_id")]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"hearing\">\r\n                                <label  class=\"control-label col-md-3\" >";
echo $this->lang->line("hearing");
echo "                                </label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[17].filters[0].field", "value" => "hearing", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[17].filters[0].operator", $operatorsList, "", "id=\"hearingOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "hearingIdHiddenFilter", "name" => "filter.filters[17].filters[0].value", "value" => "", "type" => "hidden"]);
echo "                                    ";
echo form_input(["id" => "hearingValue", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("hearing")]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"event\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("event");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[18].filters[0].field", "value" => "event", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[18].filters[0].operator", $operatorsList, "", "id=\"eventOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "eventIdHiddenFilter", "name" => "filter.filters[18].filters[0].value", "value" => "", "type" => "hidden"]);
echo "                                    ";
echo form_input(["id" => "eventValue", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("event")]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n\r\n\r\n\r\n\r\n                        <div class=\"row no-margin\">\r\n                            <div class=\"form-group row col-md-6\" sf-field=\"createdByName\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("created_by");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[12].filters[0].field", "value" => "createdByName", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[12].filters[0].operator", $operatorsText, "contains", "id=\"createdByOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "createdByValue", "name" => "filter.filters[12].filters[0].value", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing")]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" id=\"createdOnContainer\" sf-field=\"createdOn\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("created_on");
echo "</label>\r\n                                <div class=\"col-md-3 \">\r\n                                    ";
echo form_input(["name" => "filter.filters[13].filters[0].field", "value" => "createdOn", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[13].filters[0].operator", "value" => "cast_eq", "class" => "sf-operator start-date-operator", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("dateOperator", $operatorsDate, "", "id=\"createdOpertator\" class=\"form-control\" onchange=\"onchangeOperatorsFiltersDate(this, 'createdOnContainer');\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "createdOnValue", "name" => "filter.filters[13].filters[0].value", "value" => "", "class" => "sf-value form-control", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                                <div class=\" col-md-5 offset-md-6 margin-top\">\r\n                                    ";
echo form_input(["name" => "filter.filters[13].logic", "value" => "and", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[13].filters[1].field", "value" => "createdOn", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[13].filters[1].operator", "value" => "cast_lte", "class" => "sf-operator2", "type" => "hidden"]);
echo "                                    ";
echo form_input(["id" => "createdOnEndValue", "name" => "filter.filters[13].filters[1].value", "value" => "", "class" => "sf-value2 form-control d-none end-date-filter", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div class=\"row no-margin\" sf-field=\"modifiedByName\">\r\n                            <div class=\"form-group row col-md-6\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("modified_by");
echo "</label>\r\n                                <div class=\"col-md-3\">\r\n                                    ";
echo form_input(["name" => "filter.filters[14].filters[0].field", "value" => "modifiedByName", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("filter.filters[14].filters[0].operator", $operatorsText, "contains", "id=\"modifiedByOpertator\" class=\"sf-operator form-control\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "modifiedByValue", "name" => "filter.filters[14].filters[0].value", "value" => "", "class" => "sf-value form-control lookup", "placeholder" => $this->lang->line("start_typing"), "title" => $this->lang->line("start_typing")]);
echo "                                </div>\r\n                            </div>\r\n                            <div class=\"form-group row col-md-6\" id=\"modifiedOnContainer\">\r\n                                <label  class=\"control-label col-md-3\">";
echo $this->lang->line("modified_on");
echo "</label>\r\n                                <div class=\"col-md-3 \">\r\n                                    ";
echo form_input(["name" => "filter.filters[15].filters[0].field", "value" => "modifiedOn", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[15].filters[0].operator", "value" => "cast_eq", "class" => "sf-operator start-date-operator", "type" => "hidden"]);
echo "                                    ";
echo form_dropdown("dateOperator", $operatorsDate, "", "id=\"modifiedOpertator\" class=\"sf-operator-list form-control\" onchange=\"onchangeOperatorsFiltersDate(this, 'modifiedOnContainer');\"");
echo "                                </div>\r\n                                <div class=\"col-md-5\">\r\n                                    ";
echo form_input(["id" => "modifiedOnValue", "name" => "filter.filters[15].filters[0].value", "value" => "", "class" => "sf-value form-control", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                                <div class=\" col-md-5 offset-md-6 margin-top\">\r\n                                    ";
echo form_input(["name" => "filter.filters[15].logic", "value" => "and", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[15].filters[1].field", "value" => "modifiedOn", "type" => "hidden"]);
echo "                                    ";
echo form_input(["name" => "filter.filters[15].filters[1].operator", "value" => "cast_lte", "class" => "sf-operator2", "type" => "hidden"]);
echo "                                    ";
echo form_input(["id" => "modifiedOnEndValue", "name" => "filter.filters[15].filters[1].value", "value" => "", "class" => "sf-value2 form-control d-none end-date-filter", "placeholder" => "YYYY-MM-DD"]);
echo "                                </div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n            <div class=\"card-footer\" id=\"submitionActions\">\r\n                <input type=\"button\" value=\"";
echo $this->lang->line("reset");
echo "\" class=\"btn btn-link no-padding\" onclick=\"resetFormFields();\" />\r\n                <input type=\"reset\" value=\"\" id=\"resetBtnHidden\" class=\"d-none\" />\r\n                <input type=\"submit\" value=\"";
echo $this->lang->line("submit");
echo "\" name=\"submit\" id=\"submit\" class=\"btn btn-secondary\" />\r\n                <input type=\"button\" value=\"";
echo $this->lang->line("submit_and_save_filter");
echo "\" id=\"submitAndSaveFilter\" ";
echo !empty($gridSavedFilters) ? "class=\"btn btn-default\"" : "class=\"btn btn-default d-none\"";
echo " />\r\n                <input type=\"button\" value=\"[";
echo $this->lang->line("hide");
echo "]\" onclick=\"hideAdvancedSearch()\" class=\"btn btn-link pull-right no-padding\" />\r\n            </div>\r\n        </div>\r\n        ";
echo form_close();
echo "        ";
if (isset($my_expenses) && !empty($my_expenses) && $my_expenses) {
    echo "            <div class=\"row\"><div class=\"col-md-12 no-padding alert alert-info centered-text\" id=\"expense-info-message\"><h6 class=\"col-md-12\">";
    echo $this->lang->line("view_expenses_related_to_allowed_accounts");
    echo "</h6></div></div>\r\n            ";
}
echo "        ";
echo form_open("", "name=\"gridFormContent\" id=\"gridFormContent\" method=\"post\" class=\"no-margin\"");
echo "        <div class=\"grid-header row gh-top\">\r\n            <div class=\"nav-full-width-0 k-padding\">
                <div class=\"row no-margin padding-15-horizontal\">
                                  <div class=\"col-md-6 col-xs-7 gh-top-title no-margin\" id=\"gridFiltersContainer\"></div>
                                                    <div class=\"col-md-6 col-xs-5 pull-right gh-top-tools\">
                                                                            <ul class=\"operations pr-5\">
                                                                                                       <li class=\"btn-group nav opts-li\"><button type=\"button\" class=\"btn btn-default\">
<i class=\"purple_color fa-solid fa-arrows-rotate\"></i>&nbsp;";
echo $this->lang->line("check_updates");
echo "</Button>\r\n  </li>
                                                                                                        <li class=\"btn-group nav opts-li\">
                                                                                                                                      <button type=\"button\" class=\"btn btn-secondary dropdown-toggle gh-top-tools-btn\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n                                    <span class=\"fa-solid fa-file-export\"></span> ";
echo $this->lang->line("export");
echo "                                    <span class=\"caret\"></span>\r\n                                </button>\r\n                                <div class=\"dropdown-menu dropdown-menu-right\">\r\n                                    <a class=\"dropdown-item\" data-callexport= \"exportExpnsesToExcel('";
echo isset($my_expenses) ? "my_expenses" : "all_expenses";
echo "');\" href=\"javascript:;\" >";
echo $this->lang->line("export_to_excel") . $this->lang->line("current_fields");
echo "</a>\r\n                                    <a class=\"dropdown-item\" data-callexport= \"exportExpnsesToExcel('";
echo isset($my_expenses) ? "my_expenses" : "all_expenses";
echo "', true);\" href=\"javascript:;\" >";
echo $this->lang->line("export_to_excel") . $this->lang->line("all_fields");
echo "</a>\r\n                                </div>\r\n                            </li>\r\n                            <li class=\"btn-group nav opts-li\">
                               <button type=\"button\" class=\"btn btn-secondary dropdown-toggle gh-top-tools-btn\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n                                <span class=\"fa-solid fa-gear\"></span>\r\n                                    ";
echo $this->lang->line("tools");
echo "                                    <span class=\"caret\"></span>\r\n                                </button>\r\n                                <div class=\"dropdown-menu dropdown-menu-right\">\r\n                                    <a class=\"dropdown-item\" href=\"";
echo site_url("vouchers/expense_add");
echo "\">";
echo $this->lang->line("record_expense");
echo "</a>\r\n                                    <a class=\"dropdown-item\" href=\"";
echo site_url("vouchers/expenses_add_bulk");
echo "\">";
echo $this->lang->line("bulk_expenses");
echo "</a>\r\n                                    <a class=\"dropdown-item\" onclick=\"manageGridFilters('Expense', 'expenseGrid', 'expenseSearchFilters', 'advancedSearchFilters');\" href=\"javascript:;\" >";
echo $this->lang->line("manage_filters");
echo "</a>\r\n                                    <a id='bulk-open-button' class=\"dropdown-item d-none\" onclick=\"confirmationDialog('bulk_change_expense_status_to_open_message',{resultHandler: bulkChangeExpenseStatus, parm: 'open'});\" href=\"javascript:;\" >";
echo $this->lang->line("bulk_open");
echo "</a>\r\n                                    <a id='bulk-approve-button' class=\"dropdown-item d-none\" onclick=\"confirmationDialog('bulk_change_expense_status_to_approved_message',{resultHandler: bulkChangeExpenseStatus, parm: 'approved'});\" href=\"javascript:;\" >";
echo $this->lang->line("bulk_approve");
echo "</a>\r\n                                </div>\r\n                            </li>\r\n                        </ul>\r\n                    </div>\r\n                </div>\r\n                <div class=\"row no-margin col-md-12 col-xs-12 grid-header-section padding-15-horizontal\">\r\n                    <div class=\"col-md-5 col-xs-4 k-grid-info-refresh-top\">\r\n                        <a href=\"javascript:;\" class=\"k-pager-refresh-top\" title=\"";
echo $this->lang->line("refresh");
echo "\"><span class=\"k-icon k-i-refresh\"></span></a>\r\n                        <span class=\"k-pager-info-top k-label-top\"></span>\r\n                    </div>\r\n                    <div class=\"col-md-7 col-xs-6 pull-right margin-bottom-10\">\r\n                        <ul class=\"operations pr-5\">\r\n                            <li class=\"opts-li\">\r\n                                ";
echo form_input(["onkeyup" => "expenseQuickSearch(event.keyCode, this.value);", "id" => "expenseLookUp", "name" => "expenseLookUp", "placeholder" => $this->lang->line("search"), "class" => "form-control search quick-search-filter"]);
echo "                            </li>\r\n                            <li class=\"opts-li margin-right\">\r\n                                <a href=\"javascript:;\" onclick=\"advancedSearchFilters();\" class=\"btn btn-link\" title=\"";
echo $this->lang->line("switch_to_advanced_search");
echo "\">\r\n                                    ";
echo $this->lang->line("advanced");
echo "                                </a>\r\n                            </li>\r\n                            <li class=\"opts-li\"><div id=\"column-picker-trigger-container\"></div></li>\r\n                        </ul>\r\n                    </div>\r\n                </div>\r\n                <div class=\"grid-header-hidden-background\"></div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"row no-margin\"><div class=\"col-md-12 no-padding ";
echo $this->session->userdata("AUTH_language") == "arabic" ? "k-rtl" : "no-padding-right";
echo "\"><div id=\"expenseGrid\" class=\"grid-container\"></div></div></div>\r\n        ";
echo form_close();
echo "        <div id=\"expenseStatusFormDialog\"></div>\r\n    </div>\r\n</div>\r\n<div id=\"gridFiltersTempContainer\" class=\"d-none\">\r\n    <h3>";
echo $this->lang->line("expenses");
echo "</h3>\r\n    <select id=\"gridFiltersList\" class=\"form-control gird-filters-list\">\r\n        <option value=\"\">";
echo $this->lang->line("all");
echo "</option>\r\n        ";
foreach ($gridSavedFilters as $gFilter) {
    echo "<option value='" . $gFilter["id"] . "' isGlobalFilter='" . $gFilter["isGlobalFilter"] . "' " . ($gFilter["id"] == $gridDefaultFilter["id"] ? "selected=\"selected\"" : "") . ">" . $gFilter["name"] . "</option>";
}
echo "    </select>\r\n    <button type=\"button\" class=\"btn btn-default save-filter-as\" aria-label=\"Add Filter\" onclick=\"addGridFilter('Expense', 'expenseGrid', 'expenseSearchFilters');\" title=\"";
echo $this->lang->line("save_search_results_in_a_filter");
echo "\">\r\n        ";
echo $this->lang->line("save_as");
echo "    </button>\r\n</div>\r\n";
$this->load->view("excel/form");
echo "<script>\r\n    var myExpenses = '";
echo isset($my_expenses) ? $my_expenses : "";
echo "';\r\n    if (myExpenses != '')\r\n        var paid_throuh_account = JSON.parse('";
echo isset($my_expenses) ? json_encode($user_paid_through_Accounts) : "";
echo "');\r\n</script>\r\n\r\n";
$gridSavedFiltersParams = false;
$gridSavedPageSize = $gridSavedColumnsSorting = false;
if ($gridSavedFiltersData) {
    $gridSavedFiltersParams = $gridSavedFiltersData["gridFilters"];
}
if ($grid_saved_details) {
    $gridSavedPageSize = $grid_saved_details["pageSize"];
    $gridSavedColumnsSorting = $grid_saved_details["sort"];
}
$this->load->view("excel/exporting_module");
echo "<script type=\"text/javascript\">\r\n    loggedUserIsAdminForGrids = '";
echo $loggedUserIsAdminForGrids;
echo "';\r\n    uriSegmentDecoded = '";
echo json_encode($this->uri->segment_array());
echo "';\r\n    gridSavedFiltersParams = '";
echo $gridSavedFiltersParams;
echo "';\r\n    gridSavedPageSize = '";
echo $gridSavedPageSize;
echo "';\r\n    gridSavedColumnsSorting = '";
echo $gridSavedColumnsSorting;
echo "';\r\n    hasAccessToExport= \"";
echo $this->is_auth->check_uri_permissions("/vouchers/", "/vouchers/expense_export_to_excel/", "money", true, true);
echo "\";\r\n</script>";

?>